baseURL = 'https://incept.md/'
languageCode = 'en'
title = 'incept.md'
disableKinds = ['taxonomy', 'term', 'RSS']
enableRobotsTXT = true

[markup.highlight]
style = 'monokai'

[params.contact]
email = 'marco.ferrarotti@gmail.com'
linkedin = 'https://www.linkedin.com/in/mjf89'
github = 'https://github.com/mjf-89'
